# Generated by Django 3.0.7 on 2021-03-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='du_date',
            new_name='due_date',
        ),
    ]
